title = "Qinghao Yang"
baseURL = "https://qinghaoyang.github.io/"
theme = "resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
address = "Chicago, IL"
email = "qinghaoyang2022@u.northwestern.edu"
favicon = "/favicon.ico"
firstName = "Qinghao"
lastName = "Yang"
phone = "1-555-555-1234"
profileImage = "img/TechChat.png"
showEducation = true
showExperience = true
showOpenSource = false
showProjects = true
showPublications = false
showQr = true
showSkills = true

[params.google]

[params.google.analytics]
trackerID = "XX-123446-01"

[[params.handles]]
link = "https://www.linkedin.com/in/qinghao-yang/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/qinghaoyang/"
name = "GitHub"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"